name: Deployement Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      
      - name: Build Next.js app
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact

      - name: Deploy on Pages
        id: deployment
        uses: actions/deploy-pages@v4


#   deploy:
# #    name: deploy
# #    needs: build
# #  
#     # runs-on: ubuntu-latest
  
#     # permissions:
#     #   pages: write
#     #   id-token: write
      
#     # environment:
#     #   name: github-pages
#     #   url: ${{ steps.deployment.outputs.page_url }}

#      steps:
#       - name: Deploy on Pages
#         uses: actions/deploy-pages@v4
